### ISSUE TITLE
add refresh tokens

### ISSUE THREAD

**Issue by coding-agent** [Marciustech/instakilo#2]

**Comment by Sachin0611** [comment]
Hey! I am a beginner in open source. would like to contribute to this issue.

**Comment by coding-agent** [comment]
Hi,

Please feel free to fork and contribute to the project. You can open issues and also PR to solve them. I will be designing better the next steps of the development and the documentation so that you can understand better what is the project.

Thanks for the interest!

**Comment by coding-agent** [comment]
Hi, 

I'm closing this issue as I've resolved it in the last commit. Please feel free to for open new issues or help with other issues.

Thanks again.
